### ISSUE TITLE
Default type

### ISSUE THREAD

**Issue by igorlovich** [hiddewie/money-kotlin#3]
@hiddewie Thank you for the library.  Any interest in supporting a default monetary type, for situations when there are modules that do not have moneta dependency ? Something along the lines (implemented for all the required methods)

``` kotlin
inline fun <reified T : MonetaryAmount> Number.ofCurrency(currency: String, monetaryContext: MonetaryContext? = null): T =
    when(T::class) {
        is MonetaryAmount -> ofCurrency(Monetary.getDefaultAmountType(), currency, monetaryContext) as T
        else -> ofCurrency(T::class.java, currency, monetaryContext)
    }
```
I can open a PR if you're ok with the approach

**Comment by hiddewie** [comment]
Hi, thanks for the issue and suggestion. 

At this moment I do not plan to ship a full monetary type, because this involves implementing the Money API. This is not easy and is best suited to a full library that plans to implement the Java money API as defined in .JSR 354.

Moneta is just one of the reference implementations, but any other implementation should work with this library. 

Are there specific problems that having a default monetary type in this library would solve for you, that would not be solved by including Moneta or another implementation of the JSR 354 API?

**Comment by igorlovich** [comment]
I think i was not clear in my suggestion. Currently we have to specify a concrete type for the generic. What I am proposing is allowing specifying the` javax.money MonetaryAmount` (the interface) as type and in that case the configured default concrete type will be chosen (`Monetary.getDefaultAmountType()`) This avoids having a dependency on a specific implementation in the domain layer.  Furthermore the  `moneta-core `dependency pulls in `okhttp` dependency (which pulls `okio`) which again should not be present in the business domain (hexagonal architecture)

These two points are the motivation behind the suggestion

**Comment by hiddewie** [comment]
Hi, thanks, this makes your suggestion more clear.

I think this is a good suggestion. A PR is welcome.

Some ideas:
- Your code example in https://github.com/hiddewie/money-kotlin/issues/3#issue-2615759031 with `is MonetaryAmount` needs a strict class equality check because every `T` will implement `MonetaryAmount`.
- I would like to avoid any state in this library. So to make `Monetary.getDefaultAmountType()` possible, can we use the JVM `ServiceLoader` (https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/ServiceLoader.html) to lookup a default monetary type provider? Then there can never be a situation when this library is not initialized yet, but the application code already calls `.ofCurrency(...)`

**Comment by igorlovich** [comment]
You're right about the class equality check. 
`Monetary.getDefaultAmountType()` is not an extension function that I have added; it is part of the `Monetary` class and already uses the `ServiceLoader` api

**Comment by hiddewie** [comment]
Implemented in https://github.com/hiddewie/money-kotlin/pull/4

**Comment by hiddewie** [comment]
I made release 2.1.0. It is being published. https://github.com/hiddewie/money-kotlin/releases/tag/2.1.0

Thanks for the work on this!
